export const BASE_URL = process.env.REACT_APP_BASE_URL;
export const CLODINARY_CLOUD_NAME = process.env.REACT_APP_CLODINARY_CLOUD_NAME;
export const CLODINARY_UPLOAD_PRESET =
  process.env.REACT_APP_CLODINARY_UPLOAD_PRESET;
